version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a pre-configured Python Docker image
    steps:
      - checkout  # Check out the repository
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest
      - run:
          name: SonarCloud analysis
          command: |
            curl -sSLo sonar-scanner.zip https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.6.2.2472/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip
            export PATH=$PWD/sonar-scanner-4.6.2.2472-linux/bin:$PATH
            sonar-scanner -Dsonar.projectKey=<your-sonarcloud-project-key> \
                          -Dsonar.organization=<your-sonarcloud-organization> \
                          -Dsonar.host.url=https://sonarcloud.io \
                          -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  build:
    jobs:
      - build
